### ISSUE TITLE
Allow positional arguments to be provided to a task

### ISSUE THREAD

**Issue by chapati23** [xanderdeseyn/hardhat-watcher#1]
Hey 👋
first of all: thanks for your work and providing this as open source to the community! 🙂

I played around with this package because I'm looking for the fastest way to re-run my tests automatically after changing them.

What I had in mind was something like this: 

```js
module.exports = {
  watcher: {
    tasks: [{ command: 'test', args: ['test/Token.ts'], params: { noCompile: true } }],
    files: ['test/Token.ts']
  },
}
```

Unfortunately, the watcher doesn't seem to support positional arguments atm which leads to _all_ tests being re-run every time a change is detected.

What I would  like is for only ONE test to be re-run to not waste time re-running other tests that haven't changed.

What do you think?

**Comment by xanderdeseyn** [comment]
Hi @chapati23, you can pick the test file to run by providing a testFiles key to params. I will make it more clear in the readme that you can do that!

**Comment by xanderdeseyn** [comment]
Actually, that wouldn't really be a general solution I suppose. I'll have a look at supporting positional arguments!

**Comment by xanderdeseyn** [comment]
Unfortunately the internal `run` command of hardhat does not allow passing positional arguments, so you will have to look up the real name. I added a section in the README explaining it. Thanks for bringing this to my attention 👍

**Comment by chapati23** [comment]
aaaah, sweet, wasn't aware you could do that! works like a charm, thanks for responding so quickly 🙏
