### ISSUE TITLE
Define multiple watch tasks

### ISSUE THREAD

**Issue by chapati23** [xanderdeseyn/hardhat-watcher#2]
hey 👋
what do you think about adding the possibility to define multiple watch tasks?

e.g. I would like to have:
1. A `yarn compile:watch` watcher task that would recompile on every change
2. A `yarn test:watch` watcher task that would rerun tests on every change

Currently, I have to choose one of the two because I can only define one `hardhat watch` task.

**Comment by xanderdeseyn** [comment]
Hmm yes that's a great idea! On it.

**Comment by xanderdeseyn** [comment]
Added in v2.0.0 👍

**Comment by chapati23** [comment]
just tried it and it works like a charm, thanks for adding this so quickly!
