### ISSUE TITLE
Allow files to be ignored in configuration

### ISSUE THREAD

**Issue by aspiers** [xanderdeseyn/hardhat-watcher#5]
For example, temporary editor lockfiles are currently treated as normal files, so execution is triggered when you start editing a file, not just when it is saved.  Another valid approach might be to ignore anything in `.gitignore` (e.g. by using `git check-ignore`).

**Comment by xanderdeseyn** [comment]
Added in https://github.com/xanderdeseyn/hardhat-watcher/releases/tag/v2.3.0
