### ISSUE TITLE
hardhat-watcher does not support run task

### ISSUE THREAD

**Issue by lewistaylor** [xanderdeseyn/hardhat-watcher#7]
I have the following configuration in my hardhat.config.js.

```
watcher: {
    local: {
      tasks: [
        "clean",
        "compile",
        {
          command: "run scripts/deploy",
          params: { noCompile: true, "--network": "localhost" },
        },
      ],
    },
  },
```

`Watcher error: task "run scripts/deploy.js" is not supported by hardhat runtime.`

As params expects a list of keyword arguments and not positional arguments, it seems like there is not support for the above command.

If I've misunderstood the usage, please let me know.

**Comment by xanderdeseyn** [comment]
The watcher runs hardhat tasks, you are trying to run a node script it seems?
