### ISSUE TITLE
Option to immediately run task after calling watch command.

### ISSUE THREAD

**Issue by xxSkyy** [xanderdeseyn/hardhat-watcher#8]
Are there a way to run task first time without any file changes? 
I.E. while testing I'd like to have first test result after calling a `yarn hardhat watch test` without changing any watched file.

**Comment by mistersingh179** [comment]
is there a way to do this?

**Comment by sahilrajput03** [comment]
i want to clear logs on each iteration of test run.., i.e., run a `clear` command.

@xanderdeseyn can we have this feature if it isn't much for you?

**Comment by xanderdeseyn** [comment]
From v2.5.0 onwards you can now use the runOnLaunch config flag :)
